version: '3.8'

networks:
  devops_project:
    driver: bridge

volumes:
  database:


services:

  database:
    container_name: database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    image: mysql:5.7
    networks:
      - devops_project
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  backend:
    restart: on-failure
    container_name: backend
    depends_on:
      - database
    image: rayenbakali/achat:1.0.0
    networks:
      - devops_project
    ports:
      - "8089:8089"